[theme]
base = "dark"
primaryColor = "#1E90FF"  # Biru muda laut
backgroundColor = "#121212"
secondaryBackgroundColor = "#181818"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501